import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import QueryProvider from "@/providers/QueryProvider";
import { Toaster } from "react-hot-toast";
import LoginSuccessToast from "@/toast/LoginSuccessToast";
import { UserProvider } from "@/context/UserContext";

const inter = Inter({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased`}>
        <QueryProvider>
          <UserProvider>
            <LoginSuccessToast />
            <Toaster position="top-right" />
            {children}
          </UserProvider>
        </QueryProvider>
      </body>
    </html>
  );
}